# Business logic: e.g., recommendation algorithms or ML calls
# Logic for generating recommendations (start with dummy data)
from typing import List, Optional

FAKE_ITEMS = [
    {"id": 1, "name": "Wireless Headphone", "category": "Electronics", "popularity": 85},
    {"id": 2, "name": "Running Shoes", "category": "sports", "popularity": 92},
    {"id": 3, "name": "Coffee Maker", "category": "home", "popularity": 78},
    {"id": 4, "name": "Yoga Mat", "category": "sports", "popularity": 65},
    {"id": 5, "name": "Smartphone Case", "category": "electronics", "popularity": 88},
    {"id": 6, "name": "Leather Wallet", "category": "accessories", "popularity": 95},
    {"id": 7, "name": "Wireless Earbuds", "category": "electronics", "popularity": 82},
    {"id": 8, "name": "Sneakers", "category": "sports", "popularity": 76},
    {"id": 9, "name": "Desk Lamp", "category": "home", "popularity": 89},
    {"id": 10, "name": "Water Bottle", "category": "health", "popularity": 68},
    {"id": 11, "name": "Gaming Chair", "category": "home", "popularity": 91},
    {"id": 12, "name": "Bluetooth Headphones", "category": "electronics", "popularity": 84},
    {"id": 13, "name": "Tennis Racket", "category": "sports", "popularity": 72},
    {"id": 14, "name": "Desk Organizer", "category": "home", "popularity": 86},
    {"id": 15, "name": "Travel Pillow", "category": "health", "popularity": 62},
    {"id": 16, "name": "Wireless Mouse", "category": "electronics", "popularity": 90},
    {"id": 17, "name": "Sunglasses", "category": "accessories", "popularity": 78},
    {"id": 18, "name": "Portable Charger", "category": "electronics", "popularity": 80},
    {"id": 19, "name": "Desk Mat", "category": "home", "popularity": 60},
    {"id": 20, "name": "Travel Blanket", "category": "health", "popularity": 70},
    {"id": 21, "name": "Personal Blender with Travel Lid", "category": "Kitchen Appliances", "popularity": 77},
    {"id": 22, "name": "Adjustable Pet Grooming Table", "category": "Pet Supplies", "popularity": 93},
    {"id": 23, "name": "Pet Safety Harness", "category": "Pet Supplies", "popularity": 74},
    {"id": 24, "name": "Granola Clusters", "category": "Food & Beverage", "popularity": 35},
    {"id": 25, "name": "Tactical Backpack", "category": "Outdoor Gear", "popularity": 34},
    {"id": 26, "name": "Breathable Face Mask Set", "category": "Health & Wellness", "popularity": 60},
    {"id": 27, "name": "Induction Cooktop", "category": "Kitchen Appliances", "popularity": 3},
    {"id": 28, "name": "Dog Walking Waist Pack", "category": "Pet Supplies", "popularity": 13},
    {"id": 29, "name": "Apple Cinnamon Breakfast Muffins", "category": "Food & Beverage", "popularity": 8},
    {"id": 30, "name": "Chocolate Coconut Protein Balls", "category": "Health & Wellness", "popularity": 22},
    {"id": 31, "name": "Air Purifier", "category": "Home & Living", "popularity": 18},
    {"id": 32, "name": "Maple Cinnamon Almonds", "category": "Food & Beverage", "popularity": 15},
    {"id": 33, "name": "Classic Baseball Cap", "category": "Clothing & Accessories", "popularity": 30},
    {"id": 34, "name": "Mango Chutney", "category": "Food & Beverage", "popularity": 91},
    {"id": 35, "name": "LED Canopy Lights", "category": "Home & Living", "popularity": 74},
    {"id": 36, "name": "Noise Reduction Headphones", "category": "Electronics", "popularity": 5},
    {"id": 37, "name": "Portable Electric Fan", "category": "Home & Living", "popularity": 38},
    {"id": 38, "name": "Video Camera", "category": "Electronics", "popularity": 82},
    {"id": 39, "name": "Chocolate Dipped Fruit", "category": "Food & Beverage", "popularity": 22},
    {"id": 40, "name": "Pasta Sauce Mix", "category": "Food & Beverage", "popularity": 51},
    {"id": 41, "name": "Luxury Memory Foam Mattress Topper", "category": "Home & Living", "popularity": 69},
    {"id": 42, "name": "Smart Water Bottle", "category": "Health & Wellness", "popularity": 73},
    {"id": 43, "name": "Foldable Yoga Mat", "category": "Fitness", "popularity": 27},
    {"id": 44, "name": "Yoga Mat", "category": "Fitness", "popularity": 57},
    {"id": 45, "name": "LED Christmas Tree Lights", "category": "Holiday & Seasonal", "popularity": 12},
    {"id": 46, "name": "Black Bean Salsa", "category": "Food & Beverage", "popularity": 31},
    {"id": 47, "name": "Caramel Apple Chips", "category": "Food & Beverage", "popularity": 90},
    {"id": 48, "name": "Fruit and Nut Bars", "category": "Health & Wellness", "popularity": 49},
    {"id": 49, "name": "Compact Hair Dryer", "category": "Personal Care", "popularity": 79},
    {"id": 50, "name": "Chocolate Syrup", "category": "Food & Beverage", "popularity": 25},
    {"id": 51, "name": "Gardening Fairy Figurines", "category": "Garden & Outdoor", "popularity": 75},
    {"id": 52, "name": "Dishwasher Safe Cutting Board", "category": "Kitchen", "popularity": 66},
    {"id": 53, "name": "Organic Granola", "category": "Food & Beverage", "popularity": 54},
    {"id": 54, "name": "Honey Sesame Chicken Mix", "category": "Food & Beverage", "popularity": 27},
    {"id": 55, "name": "Fresh Cilantro", "category": "Groceries", "popularity": 58},
    {"id": 56, "name": "Roasted Garlic", "category": "Groceries", "popularity": 95},
    {"id": 57, "name": "Dark Chocolate Raisins", "category": "Food & Beverage", "popularity": 82},
    {"id": 58, "name": "Marinara Parmesan Baked Ziti", "category": "Food & Beverage", "popularity": 3},
    {"id": 59, "name": "Cold Brew Coffee Concentrate", "category": "Food & Beverage", "popularity": 94},
    {"id": 60, "name": "Wooden Puzzle Game", "category": "Toys & Games", "popularity": 85},
    {"id": 61, "name": "Wall Decals for Kids", "category": "Home Decor", "popularity": 87},
    {"id": 62, "name": "Magnet Travel Fridge Magnets", "category": "Travel Accessories", "popularity": 19},
    {"id": 63, "name": "Spicy Vegetable Sushi Rolls", "category": "Food & Beverage", "popularity": 0},
    {"id": 64, "name": "Pet Activity Tracker", "category": "Pet Supplies", "popularity": 33},
    {"id": 65, "name": "Dill Pickle Chips", "category": "Food & Beverage", "popularity": 2},
    {"id": 66, "name": "Adjustable Bar Stools", "category": "Furniture", "popularity": 36},
    {"id": 67, "name": "Outdoor Inflatable Pool", "category": "Outdoor & Recreation", "popularity": 16},
    {"id": 68, "name": "Sports Windbreaker", "category": "Clothing", "popularity": 76},
    {"id": 69, "name": "Fitness Resistance Bands Kit", "category": "Fitness", "popularity": 5},
    {"id": 70, "name": "High-Quality Yoga Mat", "category": "Fitness", "popularity": 96},
    {"id": 71, "name": "Non-Stick Crepe Pan", "category": "Kitchen", "popularity": 17},
    {"id": 72, "name": "Diced Tomatoes (canned)", "category": "Groceries", "popularity": 31},
    {"id": 73, "name": "Pet Hair Removal Brush", "category": "Pet Supplies", "popularity": 63},
    {"id": 74, "name": "Buffalo Chicken Dip", "category": "Food & Beverage", "popularity": 17},
    {"id": 75, "name": "Teriyaki Beef Strips", "category": "Food & Beverage", "popularity": 67},
    {"id": 76, "name": "Ready-to-Eat Chili", "category": "Food & Beverage", "popularity": 0},
    {"id": 77, "name": "Eco-Friendly Cleaning Cloths", "category": "Household Supplies", "popularity": 56},
    {"id": 78, "name": "Jasmine Rice", "category": "Groceries", "popularity": 31},
    {"id": 79, "name": "Beef Enchilada Casserole", "category": "Food & Beverage", "popularity": 67},
    {"id": 80, "name": "Banana Chips", "category": "Food & Beverage", "popularity": 83},
    {"id": 81, "name": "Zesty Garlic Marinade", "category": "Food & Beverage", "popularity": 83},
    {"id": 82, "name": "Chocolate Syrup", "category": "Food & Beverage", "popularity": 59},
    {"id": 83, "name": "Fresh Strawberries", "category": "Groceries", "popularity": 100},
    {"id": 84, "name": "Buffalo Style Cauliflower Bites", "category": "Food & Beverage", "popularity": 56},
    {"id": 85, "name": "Spinach Artichoke Dip", "category": "Food & Beverage", "popularity": 17},
    {"id": 86, "name": "Faux Fur Coat", "category": "Clothing", "popularity": 91},
    {"id": 87, "name": "Desk Organizer Set", "category": "Office Supplies", "popularity": 77},
    {"id": 88, "name": "Coconut Milk", "category": "Groceries", "popularity": 4},
    {"id": 89, "name": "Herb Seasoned Couscous", "category": "Food & Beverage", "popularity": 92},
    {"id": 90, "name": "Maple Cinnamon Granola Bars", "category": "Food & Beverage", "popularity": 84},
    {"id": 91, "name": "Mediterranean Chickpea Bowl", "category": "Food & Beverage", "popularity": 6},
    {"id": 92, "name": "Mushroom Soup (canned)", "category": "Groceries", "popularity": 83},
    {"id": 93, "name": "Peach Mango Smoothie", "category": "Beverages", "popularity": 61},
    {"id": 94, "name": "Black Bean Spaghetti", "category": "Food & Beverage", "popularity": 48},
    {"id": 95, "name": "Multi-Purpose Marine Rope", "category": "Outdoor Gear", "popularity": 92},
    {"id": 96, "name": "Insulated Lunch Bag", "category": "Travel Accessories", "popularity": 19},
    {"id": 97, "name": "Teriyaki Chicken Bowl", "category": "Food & Beverage", "popularity": 45},
    {"id": 98, "name": "Kid's Fruit Snacks", "category": "Food & Beverage", "popularity": 81},
    {"id": 99, "name": "LED Disco Ball Light", "category": "Home Decor", "popularity": 96},
    {"id": 100, "name": "Fashionable Fanny Pack", "category": "Clothing Accessories", "popularity": 42}
]

async def get_recommendations(user_id: Optional[int], limit: int = 5) -> List[dict]:
    if user_id is None:
        sorted_items = sorted(FAKE_ITEMS, key=lambda x: x['popularity'], reverse=True)
    else:
        def score(item):
            base = item['popularity']
            if (item["popularity"] % 2) == (user_id % 2):
                base += 1.1
            return base
        
        sorted_items = sorted(FAKE_ITEMS, key=score, reverse=True)
    
    return sorted_items[:limit]